// Code generated by cmd/vkgen from vk.xml; DO NOT EDIT.
//
// These encoders implement the Mesa Venus wire format (see package
// internal/vncs for the per-primitive Mesa citations).

package proof

import "github.com/go-virtio/venus/internal/vncs"

// VkApplicationInfo is the pure-Go input for the generated EncodeVkApplicationInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkApplicationInfo struct {
	PApplicationName   string
	ApplicationVersion uint32
	PEngineName        string
	EngineVersion      uint32
	ApiVersion         uint32
}

// VkInstanceCreateInfo is the pure-Go input for the generated EncodeVkInstanceCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkInstanceCreateInfo struct {
	Flags                   uint32
	PApplicationInfo        *VkApplicationInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
}

// VkDeviceQueueCreateInfo is the pure-Go input for the generated EncodeVkDeviceQueueCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkDeviceQueueCreateInfo struct {
	Flags            uint32
	QueueFamilyIndex uint32
	QueueCount       uint32
	PQueuePriorities []float32
}

// VkDeviceCreateInfo is the pure-Go input for the generated EncodeVkDeviceCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkDeviceCreateInfo struct {
	Flags                   uint32
	QueueCreateInfoCount    uint32
	PQueueCreateInfos       []VkDeviceQueueCreateInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
}

// VkExtent3D is the pure-Go input for the generated EncodeVkExtent3D
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkExtent3D struct {
	Width  uint32
	Height uint32
	Depth  uint32
}

// VkImageCreateInfo is the pure-Go input for the generated EncodeVkImageCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkImageCreateInfo struct {
	Flags                 uint32
	ImageType             int32
	Format                int32
	Extent                VkExtent3D
	MipLevels             uint32
	ArrayLayers           uint32
	Samples               uint32
	Tiling                int32
	Usage                 uint32
	SharingMode           int32
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	InitialLayout         int32
}

// VkMemoryAllocateInfo is the pure-Go input for the generated EncodeVkMemoryAllocateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkMemoryAllocateInfo struct {
	AllocationSize  uint64
	MemoryTypeIndex uint32
}

// VkCommandPoolCreateInfo is the pure-Go input for the generated EncodeVkCommandPoolCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandPoolCreateInfo struct {
	Flags            uint32
	QueueFamilyIndex uint32
}

// VkCommandBufferAllocateInfo is the pure-Go input for the generated EncodeVkCommandBufferAllocateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandBufferAllocateInfo struct {
	CommandPool        uint64
	Level              int32
	CommandBufferCount uint32
}

// VkCommandBufferInheritanceInfo is the pure-Go input for the generated EncodeVkCommandBufferInheritanceInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandBufferInheritanceInfo struct {
	RenderPass           uint64
	Subpass              uint32
	Framebuffer          uint64
	OcclusionQueryEnable bool
	QueryFlags           uint32
	PipelineStatistics   uint32
}

// VkCommandBufferBeginInfo is the pure-Go input for the generated EncodeVkCommandBufferBeginInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandBufferBeginInfo struct {
	Flags            uint32
	PInheritanceInfo *VkCommandBufferInheritanceInfo
}

// VkImageSubresourceRange is the pure-Go input for the generated EncodeVkImageSubresourceRange
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkImageSubresourceRange struct {
	AspectMask     uint32
	BaseMipLevel   uint32
	LevelCount     uint32
	BaseArrayLayer uint32
	LayerCount     uint32
}

// VkClearColorValue is the pure-Go input for the generated EncodeVkClearColorValue union
// encoder. Tag selects the active arm (0=float32, 1=int32, 2=uint32).
type VkClearColorValue struct {
	Tag     uint32
	Float32 [4]float32
	Int32   [4]int32
	Uint32  [4]uint32
}

// VkSubmitInfo is the pure-Go input for the generated EncodeVkSubmitInfo
// encoder. sType is fixed by the struct identity; PNext is the
// (possibly empty) extension chain, encoded via EncodePNextChain.
type VkSubmitInfo struct {
	PNext                []vncs.PNextNode
	WaitSemaphoreCount   uint32
	PWaitSemaphores      []uint64
	PWaitDstStageMask    []uint32
	CommandBufferCount   uint32
	PCommandBuffers      []uint64
	SignalSemaphoreCount uint32
	PSignalSemaphores    []uint64
}

// VkImageMemoryBarrier is the pure-Go input for the generated EncodeVkImageMemoryBarrier
// encoder. sType is fixed by the struct identity; PNext is the
// (possibly empty) extension chain, encoded via EncodePNextChain.
type VkImageMemoryBarrier struct {
	PNext               []vncs.PNextNode
	SrcAccessMask       uint32
	DstAccessMask       uint32
	OldLayout           int32
	NewLayout           int32
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Image               uint64
	SubresourceRange    VkImageSubresourceRange
}

// VkMemoryBarrier is the pure-Go input for the generated EncodeVkMemoryBarrier
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkMemoryBarrier struct {
	SrcAccessMask uint32
	DstAccessMask uint32
}

// VkBufferMemoryBarrier is the pure-Go input for the generated EncodeVkBufferMemoryBarrier
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkBufferMemoryBarrier struct {
	SrcAccessMask       uint32
	DstAccessMask       uint32
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Buffer              uint64
	Offset              uint64
	Size                uint64
}

// VkMemoryRequirements is the pure-Go input for the generated EncodeVkMemoryRequirements
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkMemoryRequirements struct {
	Size           uint64
	Alignment      uint64
	MemoryTypeBits uint32
}

// VkPhysicalDeviceLimits is the pure-Go input for the generated EncodeVkPhysicalDeviceLimits
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceLimits struct {
	MaxImageDimension1D          uint32
	MaxImageDimension2D          uint32
	MaxImageDimension3D          uint32
	MaxImageDimensionCube        uint32
	MaxImageArrayLayers          uint32
	MaxTexelBufferElements       uint32
	BufferImageGranularity       uint64
	MaxComputeWorkGroupCount     [3]uint32
	MaxSamplerLodBias            float32
	MinMemoryMapAlignment        uint64
	MinTexelOffset               int32
	FramebufferColorSampleCounts uint32
	TimestampComputeAndGraphics  bool
	PointSizeRange               [2]float32
	NonCoherentAtomSize          uint64
}

// VkPhysicalDeviceSparseProperties is the pure-Go input for the generated EncodeVkPhysicalDeviceSparseProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceSparseProperties struct {
	ResidencyStandard2DBlockShape            bool
	ResidencyStandard2DMultisampleBlockShape bool
	ResidencyStandard3DBlockShape            bool
	ResidencyAlignedMipSize                  bool
	ResidencyNonResidentStrict               bool
}

// VkPhysicalDeviceProperties is the pure-Go input for the generated EncodeVkPhysicalDeviceProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceProperties struct {
	ApiVersion        uint32
	DriverVersion     uint32
	VendorID          uint32
	DeviceID          uint32
	DeviceType        int32
	DeviceName        string
	PipelineCacheUUID []byte
	Limits            VkPhysicalDeviceLimits
	SparseProperties  VkPhysicalDeviceSparseProperties
}

// VkMemoryType is the pure-Go input for the generated EncodeVkMemoryType
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkMemoryType struct {
	PropertyFlags uint32
	HeapIndex     uint32
}

// VkMemoryHeap is the pure-Go input for the generated EncodeVkMemoryHeap
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkMemoryHeap struct {
	Size  uint64
	Flags uint32
}

// VkPhysicalDeviceMemoryProperties is the pure-Go input for the generated EncodeVkPhysicalDeviceMemoryProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceMemoryProperties struct {
	MemoryTypeCount uint32
	MemoryTypes     [32]VkMemoryType
	MemoryHeapCount uint32
	MemoryHeaps     [16]VkMemoryHeap
}

// VkQueueFamilyProperties is the pure-Go input for the generated EncodeVkQueueFamilyProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkQueueFamilyProperties struct {
	QueueFlags                  uint32
	QueueCount                  uint32
	TimestampValidBits          uint32
	MinImageTransferGranularity VkExtent3D
}

// VkProtectedSubmitInfo is the pure-Go input for the generated EncodeVkProtectedSubmitInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkProtectedSubmitInfo struct {
	ProtectedSubmit bool
}

// EncodeVkApplicationInfo encodes a VkApplicationInfo onto enc, following Mesa
// vn_encode_VkApplicationInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkApplicationInfo(enc *vncs.Encoder, v *VkApplicationInfo) {
	enc.EncodeInt32(0)             // sType = VK_STRUCTURE_TYPE_APPLICATION_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	if v.PApplicationName != "" {
		enc.EncodeString(v.PApplicationName)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.ApplicationVersion)
	if v.PEngineName != "" {
		enc.EncodeString(v.PEngineName)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EngineVersion)
	enc.EncodeUint32(v.ApiVersion)
}

// EncodeVkInstanceCreateInfo encodes a VkInstanceCreateInfo onto enc, following Mesa
// vn_encode_VkInstanceCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkInstanceCreateInfo(enc *vncs.Encoder, v *VkInstanceCreateInfo) {
	enc.EncodeInt32(1)             // sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	if enc.EncodeSimplePointer(v.PApplicationInfo != nil) {
		EncodeVkApplicationInfo(enc, v.PApplicationInfo)
	}
	enc.EncodeUint32(v.EnabledLayerCount)
	if len(v.PpEnabledLayerNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledLayerNames)))
		for _, s := range v.PpEnabledLayerNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledExtensionCount)
	if len(v.PpEnabledExtensionNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledExtensionNames)))
		for _, s := range v.PpEnabledExtensionNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkDeviceQueueCreateInfo encodes a VkDeviceQueueCreateInfo onto enc, following Mesa
// vn_encode_VkDeviceQueueCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkDeviceQueueCreateInfo(enc *vncs.Encoder, v *VkDeviceQueueCreateInfo) {
	enc.EncodeInt32(2)             // sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueFamilyIndex)
	enc.EncodeUint32(v.QueueCount)
	if len(v.PQueuePriorities) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueuePriorities)))
		enc.EncodeFloat32Array(v.PQueuePriorities)
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkDeviceCreateInfo encodes a VkDeviceCreateInfo onto enc, following Mesa
// vn_encode_VkDeviceCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkDeviceCreateInfo(enc *vncs.Encoder, v *VkDeviceCreateInfo) {
	enc.EncodeInt32(3)             // sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueCreateInfoCount)
	if len(v.PQueueCreateInfos) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueueCreateInfos)))
		for i := range v.PQueueCreateInfos {
			EncodeVkDeviceQueueCreateInfo(enc, &v.PQueueCreateInfos[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledLayerCount)
	if len(v.PpEnabledLayerNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledLayerNames)))
		for _, s := range v.PpEnabledLayerNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledExtensionCount)
	if len(v.PpEnabledExtensionNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledExtensionNames)))
		for _, s := range v.PpEnabledExtensionNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkExtent3D encodes a VkExtent3D onto enc, following Mesa
// vn_encode_VkExtent3D: members in declaration order (no sType/pNext).
func EncodeVkExtent3D(enc *vncs.Encoder, v *VkExtent3D) {
	enc.EncodeUint32(v.Width)
	enc.EncodeUint32(v.Height)
	enc.EncodeUint32(v.Depth)
}

// EncodeVkImageCreateInfo encodes a VkImageCreateInfo onto enc, following Mesa
// vn_encode_VkImageCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkImageCreateInfo(enc *vncs.Encoder, v *VkImageCreateInfo) {
	enc.EncodeInt32(14)            // sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeInt32(v.ImageType) // enum VkImageType
	enc.EncodeInt32(v.Format)    // enum VkFormat
	EncodeVkExtent3D(enc, &v.Extent)
	enc.EncodeUint32(v.MipLevels)
	enc.EncodeUint32(v.ArrayLayers)
	enc.EncodeFlags(v.Samples)
	enc.EncodeInt32(v.Tiling) // enum VkImageTiling
	enc.EncodeFlags(v.Usage)
	enc.EncodeInt32(v.SharingMode) // enum VkSharingMode
	enc.EncodeUint32(v.QueueFamilyIndexCount)
	if len(v.PQueueFamilyIndices) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueueFamilyIndices)))
		enc.EncodeUint32Array(v.PQueueFamilyIndices)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeInt32(v.InitialLayout) // enum VkImageLayout
}

// EncodeVkMemoryAllocateInfo encodes a VkMemoryAllocateInfo onto enc, following Mesa
// vn_encode_VkMemoryAllocateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkMemoryAllocateInfo(enc *vncs.Encoder, v *VkMemoryAllocateInfo) {
	enc.EncodeInt32(5)             // sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeDeviceSize(v.AllocationSize)
	enc.EncodeUint32(v.MemoryTypeIndex)
}

// EncodeVkCommandPoolCreateInfo encodes a VkCommandPoolCreateInfo onto enc, following Mesa
// vn_encode_VkCommandPoolCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandPoolCreateInfo(enc *vncs.Encoder, v *VkCommandPoolCreateInfo) {
	enc.EncodeInt32(39)            // sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueFamilyIndex)
}

// EncodeVkCommandBufferAllocateInfo encodes a VkCommandBufferAllocateInfo onto enc, following Mesa
// vn_encode_VkCommandBufferAllocateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandBufferAllocateInfo(enc *vncs.Encoder, v *VkCommandBufferAllocateInfo) {
	enc.EncodeInt32(40)             // sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO
	enc.EncodeSimplePointer(false)  // pNext = NULL
	enc.EncodeHandle(v.CommandPool) // handle VkCommandPool
	enc.EncodeInt32(v.Level)        // enum VkCommandBufferLevel
	enc.EncodeUint32(v.CommandBufferCount)
}

// EncodeVkCommandBufferInheritanceInfo encodes a VkCommandBufferInheritanceInfo onto enc, following Mesa
// vn_encode_VkCommandBufferInheritanceInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandBufferInheritanceInfo(enc *vncs.Encoder, v *VkCommandBufferInheritanceInfo) {
	enc.EncodeInt32(41)            // sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeHandle(v.RenderPass) // handle VkRenderPass
	enc.EncodeUint32(v.Subpass)
	enc.EncodeHandle(v.Framebuffer) // handle VkFramebuffer
	enc.EncodeBool32(v.OcclusionQueryEnable)
	enc.EncodeFlags(v.QueryFlags)
	enc.EncodeFlags(v.PipelineStatistics)
}

// EncodeVkCommandBufferBeginInfo encodes a VkCommandBufferBeginInfo onto enc, following Mesa
// vn_encode_VkCommandBufferBeginInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandBufferBeginInfo(enc *vncs.Encoder, v *VkCommandBufferBeginInfo) {
	enc.EncodeInt32(42)            // sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	if enc.EncodeSimplePointer(v.PInheritanceInfo != nil) {
		EncodeVkCommandBufferInheritanceInfo(enc, v.PInheritanceInfo)
	}
}

// EncodeVkImageSubresourceRange encodes a VkImageSubresourceRange onto enc, following Mesa
// vn_encode_VkImageSubresourceRange: members in declaration order (no sType/pNext).
func EncodeVkImageSubresourceRange(enc *vncs.Encoder, v *VkImageSubresourceRange) {
	enc.EncodeFlags(v.AspectMask)
	enc.EncodeUint32(v.BaseMipLevel)
	enc.EncodeUint32(v.LevelCount)
	enc.EncodeUint32(v.BaseArrayLayer)
	enc.EncodeUint32(v.LayerCount)
}

// EncodeVkClearColorValue encodes the VkClearColorValue union onto enc, following Mesa
// vn_encode_VkClearColorValue_tag: uint32 tag + array_size(4) + the 4-element arm.
func EncodeVkClearColorValue(enc *vncs.Encoder, v *VkClearColorValue) {
	enc.EncodeUint32(v.Tag)
	enc.EncodeArraySize(4)
	switch v.Tag {
	case 0:
		enc.EncodeFloat32Array(v.Float32[:])
	case 1:
		enc.EncodeInt32Array(v.Int32[:])
	case 2:
		enc.EncodeUint32Array(v.Uint32[:])
	}
}

// EncodeVkSubmitInfo encodes a VkSubmitInfo onto enc, following Mesa
// vn_encode_VkSubmitInfo: sType (int32) + the pNext chain (vn_encode_VkSubmitInfo_pnext)
// + self members in declaration order.
func EncodeVkSubmitInfo(enc *vncs.Encoder, v *VkSubmitInfo) {
	enc.EncodeInt32(4)            // sType = VK_STRUCTURE_TYPE_SUBMIT_INFO
	enc.EncodePNextChain(v.PNext) // pNext extension chain
	enc.EncodeUint32(v.WaitSemaphoreCount)
	if len(v.PWaitSemaphores) != 0 {
		enc.EncodeArraySize(uint64(len(v.PWaitSemaphores)))
		for i := range v.PWaitSemaphores {
			enc.EncodeHandle(v.PWaitSemaphores[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	if len(v.PWaitDstStageMask) != 0 {
		enc.EncodeArraySize(uint64(len(v.PWaitDstStageMask)))
		for i := range v.PWaitDstStageMask {
			enc.EncodeFlags(v.PWaitDstStageMask[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.CommandBufferCount)
	if len(v.PCommandBuffers) != 0 {
		enc.EncodeArraySize(uint64(len(v.PCommandBuffers)))
		for i := range v.PCommandBuffers {
			enc.EncodeHandle(v.PCommandBuffers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.SignalSemaphoreCount)
	if len(v.PSignalSemaphores) != 0 {
		enc.EncodeArraySize(uint64(len(v.PSignalSemaphores)))
		for i := range v.PSignalSemaphores {
			enc.EncodeHandle(v.PSignalSemaphores[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkImageMemoryBarrier encodes a VkImageMemoryBarrier onto enc, following Mesa
// vn_encode_VkImageMemoryBarrier: sType (int32) + the pNext chain (vn_encode_VkImageMemoryBarrier_pnext)
// + self members in declaration order.
func EncodeVkImageMemoryBarrier(enc *vncs.Encoder, v *VkImageMemoryBarrier) {
	enc.EncodeInt32(45)           // sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
	enc.EncodePNextChain(v.PNext) // pNext extension chain
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
	enc.EncodeInt32(v.OldLayout) // enum VkImageLayout
	enc.EncodeInt32(v.NewLayout) // enum VkImageLayout
	enc.EncodeUint32(v.SrcQueueFamilyIndex)
	enc.EncodeUint32(v.DstQueueFamilyIndex)
	enc.EncodeHandle(v.Image) // handle VkImage
	EncodeVkImageSubresourceRange(enc, &v.SubresourceRange)
}

// EncodeVkMemoryBarrier encodes a VkMemoryBarrier onto enc, following Mesa
// vn_encode_VkMemoryBarrier: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkMemoryBarrier(enc *vncs.Encoder, v *VkMemoryBarrier) {
	enc.EncodeInt32(46)            // sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
}

// EncodeVkBufferMemoryBarrier encodes a VkBufferMemoryBarrier onto enc, following Mesa
// vn_encode_VkBufferMemoryBarrier: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkBufferMemoryBarrier(enc *vncs.Encoder, v *VkBufferMemoryBarrier) {
	enc.EncodeInt32(44)            // sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
	enc.EncodeUint32(v.SrcQueueFamilyIndex)
	enc.EncodeUint32(v.DstQueueFamilyIndex)
	enc.EncodeHandle(v.Buffer) // handle VkBuffer
	enc.EncodeDeviceSize(v.Offset)
	enc.EncodeDeviceSize(v.Size)
}

// EncodeVkMemoryRequirementsPartial encodes the request-side _partial skeleton of a
// VkMemoryRequirements, following Mesa vn_encode_VkMemoryRequirements_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkMemoryRequirementsPartial(enc *vncs.Encoder, v *VkMemoryRequirements) {
}

// EncodeVkMemoryTypePartial encodes the request-side _partial skeleton of a
// VkMemoryType, following Mesa vn_encode_VkMemoryType_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkMemoryTypePartial(enc *vncs.Encoder, v *VkMemoryType) {
}

// EncodeVkMemoryHeapPartial encodes the request-side _partial skeleton of a
// VkMemoryHeap, following Mesa vn_encode_VkMemoryHeap_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkMemoryHeapPartial(enc *vncs.Encoder, v *VkMemoryHeap) {
}

// EncodeVkPhysicalDeviceMemoryPropertiesPartial encodes the request-side _partial skeleton of a
// VkPhysicalDeviceMemoryProperties, following Mesa vn_encode_VkPhysicalDeviceMemoryProperties_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkPhysicalDeviceMemoryPropertiesPartial(enc *vncs.Encoder, v *VkPhysicalDeviceMemoryProperties) {
	enc.EncodeArraySize(32)
	for i := range v.MemoryTypes {
		EncodeVkMemoryTypePartial(enc, &v.MemoryTypes[i])
	}
	enc.EncodeArraySize(16)
	for i := range v.MemoryHeaps {
		EncodeVkMemoryHeapPartial(enc, &v.MemoryHeaps[i])
	}
}

// EncodeVkExtent3DPartial encodes the request-side _partial skeleton of a
// VkExtent3D, following Mesa vn_encode_VkExtent3D_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkExtent3DPartial(enc *vncs.Encoder, v *VkExtent3D) {
}

// EncodeVkQueueFamilyPropertiesPartial encodes the request-side _partial skeleton of a
// VkQueueFamilyProperties, following Mesa vn_encode_VkQueueFamilyProperties_partial: scalar members are
// skipped; nested-struct and fixed-struct-array members are walked.
func EncodeVkQueueFamilyPropertiesPartial(enc *vncs.Encoder, v *VkQueueFamilyProperties) {
	EncodeVkExtent3DPartial(enc, &v.MinImageTransferGranularity)
}

// Encode_vkCreateInstance frames the vkCreateInstance command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateInstance_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateInstance.
func Encode_vkCreateInstance(enc *vncs.Encoder, cmdFlags uint32, pCreateInfo *VkInstanceCreateInfo, pInstance uint64) {
	enc.EncodeInt32(0) // cmd_type = VK_COMMAND_TYPE_vkCreateInstance_EXT
	enc.EncodeFlags(cmdFlags)
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkInstanceCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pInstance != 0) {
		enc.EncodeHandle(pInstance)
	}
}

// Encode_vkEnumeratePhysicalDevices frames the vkEnumeratePhysicalDevices command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkEnumeratePhysicalDevices.
func Encode_vkEnumeratePhysicalDevices(enc *vncs.Encoder, cmdFlags uint32, instance uint64, pPhysicalDeviceCount uint32, pPhysicalDevices []uint64) {
	enc.EncodeInt32(2) // cmd_type = VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(instance) // handle VkInstance
	if enc.EncodeSimplePointer(true) {
		enc.EncodeUint32(pPhysicalDeviceCount)
	}
	if len(pPhysicalDevices) != 0 {
		enc.EncodeArraySize(uint64(len(pPhysicalDevices)))
		for i := range pPhysicalDevices {
			enc.EncodeHandle(pPhysicalDevices[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkGetPhysicalDeviceMemoryProperties frames the vkGetPhysicalDeviceMemoryProperties command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkGetPhysicalDeviceMemoryProperties_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkGetPhysicalDeviceMemoryProperties.
func Encode_vkGetPhysicalDeviceMemoryProperties(enc *vncs.Encoder, cmdFlags uint32, physicalDevice uint64, pMemoryProperties *VkPhysicalDeviceMemoryProperties) {
	enc.EncodeInt32(8) // cmd_type = VK_COMMAND_TYPE_vkGetPhysicalDeviceMemoryProperties_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(physicalDevice) // handle VkPhysicalDevice
	if enc.EncodeSimplePointer(pMemoryProperties != nil) {
		EncodeVkPhysicalDeviceMemoryPropertiesPartial(enc, pMemoryProperties)
	}
}

// Encode_vkGetPhysicalDeviceQueueFamilyProperties frames the vkGetPhysicalDeviceQueueFamilyProperties command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkGetPhysicalDeviceQueueFamilyProperties_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkGetPhysicalDeviceQueueFamilyProperties.
func Encode_vkGetPhysicalDeviceQueueFamilyProperties(enc *vncs.Encoder, cmdFlags uint32, physicalDevice uint64, pQueueFamilyPropertyCount uint32, pQueueFamilyProperties []VkQueueFamilyProperties) {
	enc.EncodeInt32(7) // cmd_type = VK_COMMAND_TYPE_vkGetPhysicalDeviceQueueFamilyProperties_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(physicalDevice) // handle VkPhysicalDevice
	if enc.EncodeSimplePointer(true) {
		enc.EncodeUint32(pQueueFamilyPropertyCount)
	}
	if len(pQueueFamilyProperties) != 0 {
		enc.EncodeArraySize(uint64(len(pQueueFamilyProperties)))
		for i := range pQueueFamilyProperties {
			EncodeVkQueueFamilyPropertiesPartial(enc, &pQueueFamilyProperties[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkCreateDevice frames the vkCreateDevice command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateDevice_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateDevice.
func Encode_vkCreateDevice(enc *vncs.Encoder, cmdFlags uint32, physicalDevice uint64, pCreateInfo *VkDeviceCreateInfo, pDevice uint64) {
	enc.EncodeInt32(11) // cmd_type = VK_COMMAND_TYPE_vkCreateDevice_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(physicalDevice) // handle VkPhysicalDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkDeviceCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pDevice != 0) {
		enc.EncodeHandle(pDevice)
	}
}

// Encode_vkGetDeviceQueue frames the vkGetDeviceQueue command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkGetDeviceQueue_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkGetDeviceQueue.
func Encode_vkGetDeviceQueue(enc *vncs.Encoder, cmdFlags uint32, device uint64, queueFamilyIndex uint32, queueIndex uint32, pQueue uint64) {
	enc.EncodeInt32(17) // cmd_type = VK_COMMAND_TYPE_vkGetDeviceQueue_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	enc.EncodeUint32(queueFamilyIndex)
	enc.EncodeUint32(queueIndex)
	if enc.EncodeSimplePointer(pQueue != 0) {
		enc.EncodeHandle(pQueue)
	}
}

// Encode_vkCreateImage frames the vkCreateImage command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateImage_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateImage.
func Encode_vkCreateImage(enc *vncs.Encoder, cmdFlags uint32, device uint64, pCreateInfo *VkImageCreateInfo, pImage uint64) {
	enc.EncodeInt32(54) // cmd_type = VK_COMMAND_TYPE_vkCreateImage_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkImageCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pImage != 0) {
		enc.EncodeHandle(pImage)
	}
}

// Encode_vkGetImageMemoryRequirements frames the vkGetImageMemoryRequirements command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkGetImageMemoryRequirements_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkGetImageMemoryRequirements.
func Encode_vkGetImageMemoryRequirements(enc *vncs.Encoder, cmdFlags uint32, device uint64, image uint64, pMemoryRequirements *VkMemoryRequirements) {
	enc.EncodeInt32(31) // cmd_type = VK_COMMAND_TYPE_vkGetImageMemoryRequirements_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	enc.EncodeHandle(image)  // handle VkImage
	if enc.EncodeSimplePointer(pMemoryRequirements != nil) {
		EncodeVkMemoryRequirementsPartial(enc, pMemoryRequirements)
	}
}

// Encode_vkAllocateMemory frames the vkAllocateMemory command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkAllocateMemory_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkAllocateMemory.
func Encode_vkAllocateMemory(enc *vncs.Encoder, cmdFlags uint32, device uint64, pAllocateInfo *VkMemoryAllocateInfo, pMemory uint64) {
	enc.EncodeInt32(21) // cmd_type = VK_COMMAND_TYPE_vkAllocateMemory_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pAllocateInfo != nil) {
		EncodeVkMemoryAllocateInfo(enc, pAllocateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pMemory != 0) {
		enc.EncodeHandle(pMemory)
	}
}

// Encode_vkBindImageMemory frames the vkBindImageMemory command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkBindImageMemory_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkBindImageMemory.
func Encode_vkBindImageMemory(enc *vncs.Encoder, cmdFlags uint32, device uint64, image uint64, memory uint64, memoryOffset uint64) {
	enc.EncodeInt32(29) // cmd_type = VK_COMMAND_TYPE_vkBindImageMemory_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	enc.EncodeHandle(image)  // handle VkImage
	enc.EncodeHandle(memory) // handle VkDeviceMemory
	enc.EncodeDeviceSize(memoryOffset)
}

// Encode_vkCreateCommandPool frames the vkCreateCommandPool command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateCommandPool_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateCommandPool.
func Encode_vkCreateCommandPool(enc *vncs.Encoder, cmdFlags uint32, device uint64, pCreateInfo *VkCommandPoolCreateInfo, pCommandPool uint64) {
	enc.EncodeInt32(85) // cmd_type = VK_COMMAND_TYPE_vkCreateCommandPool_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkCommandPoolCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pCommandPool != 0) {
		enc.EncodeHandle(pCommandPool)
	}
}

// Encode_vkAllocateCommandBuffers frames the vkAllocateCommandBuffers command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkAllocateCommandBuffers_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkAllocateCommandBuffers.
func Encode_vkAllocateCommandBuffers(enc *vncs.Encoder, cmdFlags uint32, device uint64, pAllocateInfo *VkCommandBufferAllocateInfo, pCommandBuffers []uint64) {
	enc.EncodeInt32(88) // cmd_type = VK_COMMAND_TYPE_vkAllocateCommandBuffers_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pAllocateInfo != nil) {
		EncodeVkCommandBufferAllocateInfo(enc, pAllocateInfo)
	}
	if len(pCommandBuffers) != 0 {
		var n uint32
		if pAllocateInfo != nil {
			n = pAllocateInfo.CommandBufferCount
		}
		enc.EncodeArraySize(uint64(n))
		for i := uint32(0); i < n; i++ {
			enc.EncodeHandle(pCommandBuffers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkBeginCommandBuffer frames the vkBeginCommandBuffer command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkBeginCommandBuffer_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkBeginCommandBuffer.
func Encode_vkBeginCommandBuffer(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64, pBeginInfo *VkCommandBufferBeginInfo) {
	enc.EncodeInt32(90) // cmd_type = VK_COMMAND_TYPE_vkBeginCommandBuffer_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
	if enc.EncodeSimplePointer(pBeginInfo != nil) {
		EncodeVkCommandBufferBeginInfo(enc, pBeginInfo)
	}
}

// Encode_vkEndCommandBuffer frames the vkEndCommandBuffer command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkEndCommandBuffer_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkEndCommandBuffer.
func Encode_vkEndCommandBuffer(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64) {
	enc.EncodeInt32(91) // cmd_type = VK_COMMAND_TYPE_vkEndCommandBuffer_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
}

// Encode_vkCmdClearColorImage frames the vkCmdClearColorImage command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCmdClearColorImage_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCmdClearColorImage.
func Encode_vkCmdClearColorImage(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64, image uint64, imageLayout int32, pColor *VkClearColorValue, rangeCount uint32, pRanges []VkImageSubresourceRange) {
	enc.EncodeInt32(119) // cmd_type = VK_COMMAND_TYPE_vkCmdClearColorImage_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
	enc.EncodeHandle(image)         // handle VkImage
	enc.EncodeInt32(imageLayout)    // enum VkImageLayout
	if enc.EncodeSimplePointer(pColor != nil) {
		EncodeVkClearColorValue(enc, pColor)
	}
	enc.EncodeUint32(rangeCount)
	if len(pRanges) != 0 {
		enc.EncodeArraySize(uint64(len(pRanges)))
		for i := range pRanges {
			EncodeVkImageSubresourceRange(enc, &pRanges[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkQueueSubmit frames the vkQueueSubmit command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkQueueSubmit_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkQueueSubmit.
func Encode_vkQueueSubmit(enc *vncs.Encoder, cmdFlags uint32, queue uint64, submitCount uint32, pSubmits []VkSubmitInfo, fence uint64) {
	enc.EncodeInt32(18) // cmd_type = VK_COMMAND_TYPE_vkQueueSubmit_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(queue) // handle VkQueue
	enc.EncodeUint32(submitCount)
	if len(pSubmits) != 0 {
		enc.EncodeArraySize(uint64(len(pSubmits)))
		for i := range pSubmits {
			EncodeVkSubmitInfo(enc, &pSubmits[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeHandle(fence) // handle VkFence
}

// Encode_vkCmdPipelineBarrier frames the vkCmdPipelineBarrier command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCmdPipelineBarrier_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCmdPipelineBarrier.
func Encode_vkCmdPipelineBarrier(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64, srcStageMask uint32, dstStageMask uint32, dependencyFlags uint32, memoryBarrierCount uint32, pMemoryBarriers []VkMemoryBarrier, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers []VkBufferMemoryBarrier, imageMemoryBarrierCount uint32, pImageMemoryBarriers []VkImageMemoryBarrier) {
	enc.EncodeInt32(126) // cmd_type = VK_COMMAND_TYPE_vkCmdPipelineBarrier_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
	enc.EncodeFlags(srcStageMask)
	enc.EncodeFlags(dstStageMask)
	enc.EncodeFlags(dependencyFlags)
	enc.EncodeUint32(memoryBarrierCount)
	if len(pMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pMemoryBarriers)))
		for i := range pMemoryBarriers {
			EncodeVkMemoryBarrier(enc, &pMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(bufferMemoryBarrierCount)
	if len(pBufferMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pBufferMemoryBarriers)))
		for i := range pBufferMemoryBarriers {
			EncodeVkBufferMemoryBarrier(enc, &pBufferMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(imageMemoryBarrierCount)
	if len(pImageMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pImageMemoryBarriers)))
		for i := range pImageMemoryBarriers {
			EncodeVkImageMemoryBarrier(enc, &pImageMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkQueueWaitIdle frames the vkQueueWaitIdle command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkQueueWaitIdle_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkQueueWaitIdle.
func Encode_vkQueueWaitIdle(enc *vncs.Encoder, cmdFlags uint32, queue uint64) {
	enc.EncodeInt32(19) // cmd_type = VK_COMMAND_TYPE_vkQueueWaitIdle_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(queue) // handle VkQueue
}

// Encode_vkWaitForFences frames the vkWaitForFences command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkWaitForFences_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkWaitForFences.
func Encode_vkWaitForFences(enc *vncs.Encoder, cmdFlags uint32, device uint64, fenceCount uint32, pFences []uint64, waitAll bool, timeout uint64) {
	enc.EncodeInt32(39) // cmd_type = VK_COMMAND_TYPE_vkWaitForFences_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	enc.EncodeUint32(fenceCount)
	if len(pFences) != 0 {
		enc.EncodeArraySize(uint64(len(pFences)))
		for i := range pFences {
			enc.EncodeHandle(pFences[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeBool32(waitAll)
	enc.EncodeUint64(timeout)
}

// VkCreateInstanceReplyCmdType is the VkCommandTypeEXT the vkCreateInstance reply echoes
// (VK_COMMAND_TYPE_vkCreateInstance_EXT).
const VkCreateInstanceReplyCmdType int32 = 0

// Decode_vkCreateInstance_reply decodes the vkCreateInstance reply, per Mesa
// vn_decode_vkCreateInstance_reply: command-type echo + VkResult +
// simple_pointer(pInstance). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateInstanceReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateInstance_reply(dec *vncs.Decoder) (cmdType int32, result int32, pInstance uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateInstance_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pInstance = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pInstance, ok
}

// VkCreateDeviceReplyCmdType is the VkCommandTypeEXT the vkCreateDevice reply echoes
// (VK_COMMAND_TYPE_vkCreateDevice_EXT).
const VkCreateDeviceReplyCmdType int32 = 11

// Decode_vkCreateDevice_reply decodes the vkCreateDevice reply, per Mesa
// vn_decode_vkCreateDevice_reply: command-type echo + VkResult +
// simple_pointer(pDevice). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateDeviceReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateDevice_reply(dec *vncs.Decoder) (cmdType int32, result int32, pDevice uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateDevice_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pDevice = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pDevice, ok
}

// VkCreateImageReplyCmdType is the VkCommandTypeEXT the vkCreateImage reply echoes
// (VK_COMMAND_TYPE_vkCreateImage_EXT).
const VkCreateImageReplyCmdType int32 = 54

// Decode_vkCreateImage_reply decodes the vkCreateImage reply, per Mesa
// vn_decode_vkCreateImage_reply: command-type echo + VkResult +
// simple_pointer(pImage). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateImageReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateImage_reply(dec *vncs.Decoder) (cmdType int32, result int32, pImage uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateImage_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pImage = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pImage, ok
}

// VkAllocateMemoryReplyCmdType is the VkCommandTypeEXT the vkAllocateMemory reply echoes
// (VK_COMMAND_TYPE_vkAllocateMemory_EXT).
const VkAllocateMemoryReplyCmdType int32 = 21

// Decode_vkAllocateMemory_reply decodes the vkAllocateMemory reply, per Mesa
// vn_decode_vkAllocateMemory_reply: command-type echo + VkResult +
// simple_pointer(pMemory). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkAllocateMemoryReplyCmdType (Mesa asserts the same equality).
func Decode_vkAllocateMemory_reply(dec *vncs.Decoder) (cmdType int32, result int32, pMemory uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkAllocateMemory_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pMemory = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pMemory, ok
}

// VkCreateCommandPoolReplyCmdType is the VkCommandTypeEXT the vkCreateCommandPool reply echoes
// (VK_COMMAND_TYPE_vkCreateCommandPool_EXT).
const VkCreateCommandPoolReplyCmdType int32 = 85

// Decode_vkCreateCommandPool_reply decodes the vkCreateCommandPool reply, per Mesa
// vn_decode_vkCreateCommandPool_reply: command-type echo + VkResult +
// simple_pointer(pCommandPool). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateCommandPoolReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateCommandPool_reply(dec *vncs.Decoder) (cmdType int32, result int32, pCommandPool uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateCommandPool_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pCommandPool = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pCommandPool, ok
}

// VkEnumeratePhysicalDevicesReplyCmdType is the VkCommandTypeEXT the vkEnumeratePhysicalDevices reply echoes
// (VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT).
const VkEnumeratePhysicalDevicesReplyCmdType int32 = 2

// Decode_vkEnumeratePhysicalDevices_reply decodes the vkEnumeratePhysicalDevices reply, per Mesa
// vn_decode_vkEnumeratePhysicalDevices_reply: command-type echo + VkResult +
// simple_pointer(pPhysicalDeviceCount)+uint32 + peeked counted pPhysicalDevices handle array.
// countOK is the count's simple_pointer flag; pPhysicalDevices is nil when the
// peeked array_size is 0 (the array_size(0) is still consumed, matching
// vn_decode_array_size_unchecked).
func Decode_vkEnumeratePhysicalDevices_reply(dec *vncs.Decoder) (cmdType int32, result int32, pPhysicalDeviceCount uint32, countOK bool, pPhysicalDevices []uint64) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pPhysicalDeviceCount = dec.DecodeUint32()
		countOK = true
	}
	if dec.PeekArraySize() != 0 {
		n := dec.DecodeArraySize(uint64(pPhysicalDeviceCount))
		pPhysicalDevices = make([]uint64, n)
		for i := range pPhysicalDevices {
			pPhysicalDevices[i] = dec.DecodeHandle()
		}
	} else {
		dec.DecodeArraySizeUnchecked() // consume the array_size(0)
	}
	return cmdType, result, pPhysicalDeviceCount, countOK, pPhysicalDevices
}

// VkBindImageMemoryReplyCmdType is the VkCommandTypeEXT the vkBindImageMemory reply echoes
// (VK_COMMAND_TYPE_vkBindImageMemory_EXT).
const VkBindImageMemoryReplyCmdType int32 = 29

// Decode_vkBindImageMemory_reply decodes the vkBindImageMemory reply, per Mesa
// vn_decode_vkBindImageMemory_reply: command-type echo + VkResult (no out-param).
func Decode_vkBindImageMemory_reply(dec *vncs.Decoder) (cmdType int32, result int32) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkBindImageMemory_EXT
	result = dec.DecodeResult()
	return cmdType, result
}

// VkBeginCommandBufferReplyCmdType is the VkCommandTypeEXT the vkBeginCommandBuffer reply echoes
// (VK_COMMAND_TYPE_vkBeginCommandBuffer_EXT).
const VkBeginCommandBufferReplyCmdType int32 = 90

// Decode_vkBeginCommandBuffer_reply decodes the vkBeginCommandBuffer reply, per Mesa
// vn_decode_vkBeginCommandBuffer_reply: command-type echo + VkResult (no out-param).
func Decode_vkBeginCommandBuffer_reply(dec *vncs.Decoder) (cmdType int32, result int32) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkBeginCommandBuffer_EXT
	result = dec.DecodeResult()
	return cmdType, result
}

// VkEndCommandBufferReplyCmdType is the VkCommandTypeEXT the vkEndCommandBuffer reply echoes
// (VK_COMMAND_TYPE_vkEndCommandBuffer_EXT).
const VkEndCommandBufferReplyCmdType int32 = 91

// Decode_vkEndCommandBuffer_reply decodes the vkEndCommandBuffer reply, per Mesa
// vn_decode_vkEndCommandBuffer_reply: command-type echo + VkResult (no out-param).
func Decode_vkEndCommandBuffer_reply(dec *vncs.Decoder) (cmdType int32, result int32) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkEndCommandBuffer_EXT
	result = dec.DecodeResult()
	return cmdType, result
}

// VkQueueWaitIdleReplyCmdType is the VkCommandTypeEXT the vkQueueWaitIdle reply echoes
// (VK_COMMAND_TYPE_vkQueueWaitIdle_EXT).
const VkQueueWaitIdleReplyCmdType int32 = 19

// Decode_vkQueueWaitIdle_reply decodes the vkQueueWaitIdle reply, per Mesa
// vn_decode_vkQueueWaitIdle_reply: command-type echo + VkResult (no out-param).
func Decode_vkQueueWaitIdle_reply(dec *vncs.Decoder) (cmdType int32, result int32) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkQueueWaitIdle_EXT
	result = dec.DecodeResult()
	return cmdType, result
}

// VkWaitForFencesReplyCmdType is the VkCommandTypeEXT the vkWaitForFences reply echoes
// (VK_COMMAND_TYPE_vkWaitForFences_EXT).
const VkWaitForFencesReplyCmdType int32 = 39

// Decode_vkWaitForFences_reply decodes the vkWaitForFences reply, per Mesa
// vn_decode_vkWaitForFences_reply: command-type echo + VkResult (no out-param).
func Decode_vkWaitForFences_reply(dec *vncs.Decoder) (cmdType int32, result int32) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkWaitForFences_EXT
	result = dec.DecodeResult()
	return cmdType, result
}

// VkGetDeviceQueueReplyCmdType is the VkCommandTypeEXT the vkGetDeviceQueue reply echoes
// (VK_COMMAND_TYPE_vkGetDeviceQueue_EXT).
const VkGetDeviceQueueReplyCmdType int32 = 17

// Decode_vkGetDeviceQueue_reply decodes the vkGetDeviceQueue reply, per Mesa
// vn_decode_vkGetDeviceQueue_reply: command-type echo + simple_pointer(pQueue)
// (no VkResult — vkGetDeviceQueue returns void). ok is the simple_pointer flag.
func Decode_vkGetDeviceQueue_reply(dec *vncs.Decoder) (cmdType int32, pQueue uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkGetDeviceQueue_EXT
	if dec.DecodeSimplePointer() {
		pQueue = dec.DecodeHandle()
		ok = true
	}
	return cmdType, pQueue, ok
}

// VkGetImageMemoryRequirementsReplyCmdType is the VkCommandTypeEXT the vkGetImageMemoryRequirements reply echoes
// (VK_COMMAND_TYPE_vkGetImageMemoryRequirements_EXT).
const VkGetImageMemoryRequirementsReplyCmdType int32 = 31

// Decode_vkGetImageMemoryRequirements_reply decodes the vkGetImageMemoryRequirements reply, per Mesa
// vn_decode_vkGetImageMemoryRequirements_reply: command-type echo + simple_pointer(pMemoryRequirements)
// + DecodeVkMemoryRequirements (no VkResult — vkGetImageMemoryRequirements returns void). ok is the
// simple_pointer flag.
func Decode_vkGetImageMemoryRequirements_reply(dec *vncs.Decoder, pMemoryRequirements *VkMemoryRequirements) (cmdType int32, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkGetImageMemoryRequirements_EXT
	if dec.DecodeSimplePointer() {
		DecodeVkMemoryRequirements(dec, pMemoryRequirements)
		ok = true
	}
	return cmdType, ok
}

// VkGetPhysicalDeviceMemoryPropertiesReplyCmdType is the VkCommandTypeEXT the vkGetPhysicalDeviceMemoryProperties reply echoes
// (VK_COMMAND_TYPE_vkGetPhysicalDeviceMemoryProperties_EXT).
const VkGetPhysicalDeviceMemoryPropertiesReplyCmdType int32 = 8

// Decode_vkGetPhysicalDeviceMemoryProperties_reply decodes the vkGetPhysicalDeviceMemoryProperties reply, per Mesa
// vn_decode_vkGetPhysicalDeviceMemoryProperties_reply: command-type echo + simple_pointer(pMemoryProperties)
// + DecodeVkPhysicalDeviceMemoryProperties (no VkResult — vkGetPhysicalDeviceMemoryProperties returns void). ok is the
// simple_pointer flag.
func Decode_vkGetPhysicalDeviceMemoryProperties_reply(dec *vncs.Decoder, pMemoryProperties *VkPhysicalDeviceMemoryProperties) (cmdType int32, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkGetPhysicalDeviceMemoryProperties_EXT
	if dec.DecodeSimplePointer() {
		DecodeVkPhysicalDeviceMemoryProperties(dec, pMemoryProperties)
		ok = true
	}
	return cmdType, ok
}

// VkGetPhysicalDeviceQueueFamilyPropertiesReplyCmdType is the VkCommandTypeEXT the vkGetPhysicalDeviceQueueFamilyProperties reply echoes
// (VK_COMMAND_TYPE_vkGetPhysicalDeviceQueueFamilyProperties_EXT).
const VkGetPhysicalDeviceQueueFamilyPropertiesReplyCmdType int32 = 7

// Decode_vkGetPhysicalDeviceQueueFamilyProperties_reply decodes the vkGetPhysicalDeviceQueueFamilyProperties reply, per Mesa
// vn_decode_vkGetPhysicalDeviceQueueFamilyProperties_reply: command-type echo + simple_pointer(pQueueFamilyPropertyCount)+uint32
// + peeked counted pQueueFamilyProperties struct array (no VkResult — void query).
// countOK is the count's simple_pointer flag; pQueueFamilyProperties is nil when the
// peeked array_size is 0.
func Decode_vkGetPhysicalDeviceQueueFamilyProperties_reply(dec *vncs.Decoder) (cmdType int32, pQueueFamilyPropertyCount uint32, countOK bool, pQueueFamilyProperties []VkQueueFamilyProperties) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkGetPhysicalDeviceQueueFamilyProperties_EXT
	if dec.DecodeSimplePointer() {
		pQueueFamilyPropertyCount = dec.DecodeUint32()
		countOK = true
	}
	if dec.PeekArraySize() != 0 {
		n := dec.DecodeArraySize(uint64(pQueueFamilyPropertyCount))
		pQueueFamilyProperties = make([]VkQueueFamilyProperties, n)
		for i := range pQueueFamilyProperties {
			DecodeVkQueueFamilyProperties(dec, &pQueueFamilyProperties[i])
		}
	} else {
		dec.DecodeArraySizeUnchecked() // consume the array_size(0)
	}
	return cmdType, pQueueFamilyPropertyCount, countOK, pQueueFamilyProperties
}

// VkAllocateCommandBuffersReplyCmdType is the VkCommandTypeEXT the vkAllocateCommandBuffers reply echoes
// (VK_COMMAND_TYPE_vkAllocateCommandBuffers_EXT).
const VkAllocateCommandBuffersReplyCmdType int32 = 88

// Decode_vkAllocateCommandBuffers_reply decodes the vkAllocateCommandBuffers reply, per Mesa
// vn_decode_vkAllocateCommandBuffers_reply: command-type echo + VkResult + peeked counted
// pCommandBuffers handle array bounded by maxCount (the caller's
// pAllocateInfo->commandBufferCount, i.e. the requested commandBufferCount). pCommandBuffers is nil
// when the peeked array_size is 0.
func Decode_vkAllocateCommandBuffers_reply(dec *vncs.Decoder, maxCount uint32) (cmdType int32, result int32, pCommandBuffers []uint64) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkAllocateCommandBuffers_EXT
	result = dec.DecodeResult()
	if dec.PeekArraySize() != 0 {
		n := dec.DecodeArraySize(uint64(maxCount))
		pCommandBuffers = make([]uint64, n)
		for i := range pCommandBuffers {
			pCommandBuffers[i] = dec.DecodeHandle()
		}
	} else {
		dec.DecodeArraySizeUnchecked() // consume the array_size(0)
	}
	return cmdType, result, pCommandBuffers
}

// DecodeVkMemoryRequirements decodes a VkMemoryRequirements from dec, following Mesa
// vn_decode_VkMemoryRequirements: members in declaration order.
func DecodeVkMemoryRequirements(dec *vncs.Decoder, v *VkMemoryRequirements) {
	v.Size = dec.DecodeDeviceSize()
	v.Alignment = dec.DecodeDeviceSize()
	v.MemoryTypeBits = dec.DecodeUint32()
}

// DecodeVkPhysicalDeviceLimits decodes a VkPhysicalDeviceLimits from dec, following Mesa
// vn_decode_VkPhysicalDeviceLimits: members in declaration order.
func DecodeVkPhysicalDeviceLimits(dec *vncs.Decoder, v *VkPhysicalDeviceLimits) {
	v.MaxImageDimension1D = dec.DecodeUint32()
	v.MaxImageDimension2D = dec.DecodeUint32()
	v.MaxImageDimension3D = dec.DecodeUint32()
	v.MaxImageDimensionCube = dec.DecodeUint32()
	v.MaxImageArrayLayers = dec.DecodeUint32()
	v.MaxTexelBufferElements = dec.DecodeUint32()
	v.BufferImageGranularity = dec.DecodeDeviceSize()
	{
		n := dec.DecodeArraySize(3)
		copy(v.MaxComputeWorkGroupCount[:], dec.DecodeUint32Array(int(n)))
	}
	v.MaxSamplerLodBias = dec.DecodeFloat32()
	v.MinMemoryMapAlignment = dec.DecodeSizeT()
	v.MinTexelOffset = dec.DecodeInt32()
	v.FramebufferColorSampleCounts = dec.DecodeFlags()
	v.TimestampComputeAndGraphics = dec.DecodeBool32()
	{
		n := dec.DecodeArraySize(2)
		copy(v.PointSizeRange[:], dec.DecodeFloat32Array(int(n)))
	}
	v.NonCoherentAtomSize = dec.DecodeDeviceSize()
}

// DecodeVkPhysicalDeviceSparseProperties decodes a VkPhysicalDeviceSparseProperties from dec, following Mesa
// vn_decode_VkPhysicalDeviceSparseProperties: members in declaration order.
func DecodeVkPhysicalDeviceSparseProperties(dec *vncs.Decoder, v *VkPhysicalDeviceSparseProperties) {
	v.ResidencyStandard2DBlockShape = dec.DecodeBool32()
	v.ResidencyStandard2DMultisampleBlockShape = dec.DecodeBool32()
	v.ResidencyStandard3DBlockShape = dec.DecodeBool32()
	v.ResidencyAlignedMipSize = dec.DecodeBool32()
	v.ResidencyNonResidentStrict = dec.DecodeBool32()
}

// DecodeVkPhysicalDeviceProperties decodes a VkPhysicalDeviceProperties from dec, following Mesa
// vn_decode_VkPhysicalDeviceProperties: members in declaration order.
func DecodeVkPhysicalDeviceProperties(dec *vncs.Decoder, v *VkPhysicalDeviceProperties) {
	v.ApiVersion = dec.DecodeUint32()
	v.DriverVersion = dec.DecodeUint32()
	v.VendorID = dec.DecodeUint32()
	v.DeviceID = dec.DecodeUint32()
	v.DeviceType = dec.DecodeInt32() // enum VkPhysicalDeviceType
	{
		n := dec.DecodeArraySize(256)
		v.DeviceName = string(dec.DecodeCharArray(int(n)))
	}
	{
		n := dec.DecodeArraySize(16)
		v.PipelineCacheUUID = dec.DecodeUint8Array(int(n))
	}
	DecodeVkPhysicalDeviceLimits(dec, &v.Limits)
	DecodeVkPhysicalDeviceSparseProperties(dec, &v.SparseProperties)
}

// DecodeVkMemoryType decodes a VkMemoryType from dec, following Mesa
// vn_decode_VkMemoryType: members in declaration order.
func DecodeVkMemoryType(dec *vncs.Decoder, v *VkMemoryType) {
	v.PropertyFlags = dec.DecodeFlags()
	v.HeapIndex = dec.DecodeUint32()
}

// DecodeVkMemoryHeap decodes a VkMemoryHeap from dec, following Mesa
// vn_decode_VkMemoryHeap: members in declaration order.
func DecodeVkMemoryHeap(dec *vncs.Decoder, v *VkMemoryHeap) {
	v.Size = dec.DecodeDeviceSize()
	v.Flags = dec.DecodeFlags()
}

// DecodeVkPhysicalDeviceMemoryProperties decodes a VkPhysicalDeviceMemoryProperties from dec, following Mesa
// vn_decode_VkPhysicalDeviceMemoryProperties: members in declaration order.
func DecodeVkPhysicalDeviceMemoryProperties(dec *vncs.Decoder, v *VkPhysicalDeviceMemoryProperties) {
	v.MemoryTypeCount = dec.DecodeUint32()
	{
		n := dec.DecodeArraySize(32)
		for i := uint64(0); i < n; i++ {
			DecodeVkMemoryType(dec, &v.MemoryTypes[i])
		}
	}
	v.MemoryHeapCount = dec.DecodeUint32()
	{
		n := dec.DecodeArraySize(16)
		for i := uint64(0); i < n; i++ {
			DecodeVkMemoryHeap(dec, &v.MemoryHeaps[i])
		}
	}
}

// DecodeVkExtent3D decodes a VkExtent3D from dec, following Mesa
// vn_decode_VkExtent3D: members in declaration order.
func DecodeVkExtent3D(dec *vncs.Decoder, v *VkExtent3D) {
	v.Width = dec.DecodeUint32()
	v.Height = dec.DecodeUint32()
	v.Depth = dec.DecodeUint32()
}

// DecodeVkQueueFamilyProperties decodes a VkQueueFamilyProperties from dec, following Mesa
// vn_decode_VkQueueFamilyProperties: members in declaration order.
func DecodeVkQueueFamilyProperties(dec *vncs.Decoder, v *VkQueueFamilyProperties) {
	v.QueueFlags = dec.DecodeFlags()
	v.QueueCount = dec.DecodeUint32()
	v.TimestampValidBits = dec.DecodeUint32()
	DecodeVkExtent3D(dec, &v.MinImageTransferGranularity)
}

// EncodeVkProtectedSubmitInfoSelf encodes just the self members of a VkProtectedSubmitInfo
// (no sType/pNext), per Mesa vn_encode_VkProtectedSubmitInfo_self — used as a pNext node.
func EncodeVkProtectedSubmitInfoSelf(enc *vncs.Encoder, v *VkProtectedSubmitInfo) {
	enc.EncodeBool32(v.ProtectedSubmit)
}

// VkProtectedSubmitInfoNode wraps v as a pNext chain node (sType VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO = 1000145000).
func VkProtectedSubmitInfoNode(v *VkProtectedSubmitInfo) vncs.PNextNode {
	return vncs.PNextNode{SType: 1000145000, EncodeSelf: func(enc *vncs.Encoder) { EncodeVkProtectedSubmitInfoSelf(enc, v) }}
}
