// Code generated by cmd/vkgen from vk.xml; DO NOT EDIT.
//
// These encoders implement the Mesa Venus wire format (see package
// internal/vncs for the per-primitive Mesa citations).

package proof

import "github.com/go-virtio/venus/internal/vncs"

// VkApplicationInfo is the pure-Go input for the generated EncodeVkApplicationInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkApplicationInfo struct {
	PApplicationName   string
	ApplicationVersion uint32
	PEngineName        string
	EngineVersion      uint32
	ApiVersion         uint32
}

// VkInstanceCreateInfo is the pure-Go input for the generated EncodeVkInstanceCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkInstanceCreateInfo struct {
	Flags                   uint32
	PApplicationInfo        *VkApplicationInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
}

// VkDeviceQueueCreateInfo is the pure-Go input for the generated EncodeVkDeviceQueueCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkDeviceQueueCreateInfo struct {
	Flags            uint32
	QueueFamilyIndex uint32
	QueueCount       uint32
	PQueuePriorities []float32
}

// VkDeviceCreateInfo is the pure-Go input for the generated EncodeVkDeviceCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkDeviceCreateInfo struct {
	Flags                   uint32
	QueueCreateInfoCount    uint32
	PQueueCreateInfos       []VkDeviceQueueCreateInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
}

// VkExtent3D is the pure-Go input for the generated EncodeVkExtent3D
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkExtent3D struct {
	Width  uint32
	Height uint32
	Depth  uint32
}

// VkImageCreateInfo is the pure-Go input for the generated EncodeVkImageCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkImageCreateInfo struct {
	Flags                 uint32
	ImageType             int32
	Format                int32
	Extent                VkExtent3D
	MipLevels             uint32
	ArrayLayers           uint32
	Samples               uint32
	Tiling                int32
	Usage                 uint32
	SharingMode           int32
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	InitialLayout         int32
}

// VkMemoryAllocateInfo is the pure-Go input for the generated EncodeVkMemoryAllocateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkMemoryAllocateInfo struct {
	AllocationSize  uint64
	MemoryTypeIndex uint32
}

// VkCommandPoolCreateInfo is the pure-Go input for the generated EncodeVkCommandPoolCreateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandPoolCreateInfo struct {
	Flags            uint32
	QueueFamilyIndex uint32
}

// VkCommandBufferAllocateInfo is the pure-Go input for the generated EncodeVkCommandBufferAllocateInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkCommandBufferAllocateInfo struct {
	CommandPool        uint64
	Level              int32
	CommandBufferCount uint32
}

// VkImageSubresourceRange is the pure-Go input for the generated EncodeVkImageSubresourceRange
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkImageSubresourceRange struct {
	AspectMask     uint32
	BaseMipLevel   uint32
	LevelCount     uint32
	BaseArrayLayer uint32
	LayerCount     uint32
}

// VkClearColorValue is the pure-Go input for the generated EncodeVkClearColorValue union
// encoder. Tag selects the active arm (0=float32, 1=int32, 2=uint32).
type VkClearColorValue struct {
	Tag     uint32
	Float32 [4]float32
	Int32   [4]int32
	Uint32  [4]uint32
}

// VkSubmitInfo is the pure-Go input for the generated EncodeVkSubmitInfo
// encoder. sType is fixed by the struct identity; PNext is the
// (possibly empty) extension chain, encoded via EncodePNextChain.
type VkSubmitInfo struct {
	PNext                []vncs.PNextNode
	WaitSemaphoreCount   uint32
	PWaitSemaphores      []uint64
	PWaitDstStageMask    []uint32
	CommandBufferCount   uint32
	PCommandBuffers      []uint64
	SignalSemaphoreCount uint32
	PSignalSemaphores    []uint64
}

// VkImageMemoryBarrier is the pure-Go input for the generated EncodeVkImageMemoryBarrier
// encoder. sType is fixed by the struct identity; PNext is the
// (possibly empty) extension chain, encoded via EncodePNextChain.
type VkImageMemoryBarrier struct {
	PNext               []vncs.PNextNode
	SrcAccessMask       uint32
	DstAccessMask       uint32
	OldLayout           int32
	NewLayout           int32
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Image               uint64
	SubresourceRange    VkImageSubresourceRange
}

// VkMemoryBarrier is the pure-Go input for the generated EncodeVkMemoryBarrier
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkMemoryBarrier struct {
	SrcAccessMask uint32
	DstAccessMask uint32
}

// VkBufferMemoryBarrier is the pure-Go input for the generated EncodeVkBufferMemoryBarrier
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkBufferMemoryBarrier struct {
	SrcAccessMask       uint32
	DstAccessMask       uint32
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Buffer              uint64
	Offset              uint64
	Size                uint64
}

// VkMemoryRequirements is the pure-Go input for the generated EncodeVkMemoryRequirements
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkMemoryRequirements struct {
	Size           uint64
	Alignment      uint64
	MemoryTypeBits uint32
}

// VkPhysicalDeviceLimits is the pure-Go input for the generated EncodeVkPhysicalDeviceLimits
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceLimits struct {
	MaxImageDimension1D          uint32
	MaxImageDimension2D          uint32
	MaxImageDimension3D          uint32
	MaxImageDimensionCube        uint32
	MaxImageArrayLayers          uint32
	MaxTexelBufferElements       uint32
	BufferImageGranularity       uint64
	MaxComputeWorkGroupCount     [3]uint32
	MaxSamplerLodBias            float32
	MinMemoryMapAlignment        uint64
	MinTexelOffset               int32
	FramebufferColorSampleCounts uint32
	TimestampComputeAndGraphics  bool
	PointSizeRange               [2]float32
	NonCoherentAtomSize          uint64
}

// VkPhysicalDeviceSparseProperties is the pure-Go input for the generated EncodeVkPhysicalDeviceSparseProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceSparseProperties struct {
	ResidencyStandard2DBlockShape            bool
	ResidencyStandard2DMultisampleBlockShape bool
	ResidencyStandard3DBlockShape            bool
	ResidencyAlignedMipSize                  bool
	ResidencyNonResidentStrict               bool
}

// VkPhysicalDeviceProperties is the pure-Go input for the generated EncodeVkPhysicalDeviceProperties
// encoder (a plain nested-by-value Vulkan struct, no sType).
type VkPhysicalDeviceProperties struct {
	ApiVersion        uint32
	DriverVersion     uint32
	VendorID          uint32
	DeviceID          uint32
	DeviceType        int32
	DeviceName        string
	PipelineCacheUUID []byte
	Limits            VkPhysicalDeviceLimits
	SparseProperties  VkPhysicalDeviceSparseProperties
}

// VkProtectedSubmitInfo is the pure-Go input for the generated EncodeVkProtectedSubmitInfo
// encoder. sType and pNext are not fields: sType is fixed by the
// struct identity and pNext is NULL (no extension chain emitted).
type VkProtectedSubmitInfo struct {
	ProtectedSubmit bool
}

// EncodeVkApplicationInfo encodes a VkApplicationInfo onto enc, following Mesa
// vn_encode_VkApplicationInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkApplicationInfo(enc *vncs.Encoder, v *VkApplicationInfo) {
	enc.EncodeInt32(0)             // sType = VK_STRUCTURE_TYPE_APPLICATION_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	if v.PApplicationName != "" {
		enc.EncodeString(v.PApplicationName)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.ApplicationVersion)
	if v.PEngineName != "" {
		enc.EncodeString(v.PEngineName)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EngineVersion)
	enc.EncodeUint32(v.ApiVersion)
}

// EncodeVkInstanceCreateInfo encodes a VkInstanceCreateInfo onto enc, following Mesa
// vn_encode_VkInstanceCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkInstanceCreateInfo(enc *vncs.Encoder, v *VkInstanceCreateInfo) {
	enc.EncodeInt32(1)             // sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	if enc.EncodeSimplePointer(v.PApplicationInfo != nil) {
		EncodeVkApplicationInfo(enc, v.PApplicationInfo)
	}
	enc.EncodeUint32(v.EnabledLayerCount)
	if len(v.PpEnabledLayerNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledLayerNames)))
		for _, s := range v.PpEnabledLayerNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledExtensionCount)
	if len(v.PpEnabledExtensionNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledExtensionNames)))
		for _, s := range v.PpEnabledExtensionNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkDeviceQueueCreateInfo encodes a VkDeviceQueueCreateInfo onto enc, following Mesa
// vn_encode_VkDeviceQueueCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkDeviceQueueCreateInfo(enc *vncs.Encoder, v *VkDeviceQueueCreateInfo) {
	enc.EncodeInt32(2)             // sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueFamilyIndex)
	enc.EncodeUint32(v.QueueCount)
	if len(v.PQueuePriorities) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueuePriorities)))
		enc.EncodeFloat32Array(v.PQueuePriorities)
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkDeviceCreateInfo encodes a VkDeviceCreateInfo onto enc, following Mesa
// vn_encode_VkDeviceCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkDeviceCreateInfo(enc *vncs.Encoder, v *VkDeviceCreateInfo) {
	enc.EncodeInt32(3)             // sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueCreateInfoCount)
	if len(v.PQueueCreateInfos) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueueCreateInfos)))
		for i := range v.PQueueCreateInfos {
			EncodeVkDeviceQueueCreateInfo(enc, &v.PQueueCreateInfos[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledLayerCount)
	if len(v.PpEnabledLayerNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledLayerNames)))
		for _, s := range v.PpEnabledLayerNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.EnabledExtensionCount)
	if len(v.PpEnabledExtensionNames) != 0 {
		enc.EncodeArraySize(uint64(len(v.PpEnabledExtensionNames)))
		for _, s := range v.PpEnabledExtensionNames {
			enc.EncodeString(s)
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkExtent3D encodes a VkExtent3D onto enc, following Mesa
// vn_encode_VkExtent3D: members in declaration order (no sType/pNext).
func EncodeVkExtent3D(enc *vncs.Encoder, v *VkExtent3D) {
	enc.EncodeUint32(v.Width)
	enc.EncodeUint32(v.Height)
	enc.EncodeUint32(v.Depth)
}

// EncodeVkImageCreateInfo encodes a VkImageCreateInfo onto enc, following Mesa
// vn_encode_VkImageCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkImageCreateInfo(enc *vncs.Encoder, v *VkImageCreateInfo) {
	enc.EncodeInt32(14)            // sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeInt32(v.ImageType) // enum VkImageType
	enc.EncodeInt32(v.Format)    // enum VkFormat
	EncodeVkExtent3D(enc, &v.Extent)
	enc.EncodeUint32(v.MipLevels)
	enc.EncodeUint32(v.ArrayLayers)
	enc.EncodeFlags(v.Samples)
	enc.EncodeInt32(v.Tiling) // enum VkImageTiling
	enc.EncodeFlags(v.Usage)
	enc.EncodeInt32(v.SharingMode) // enum VkSharingMode
	enc.EncodeUint32(v.QueueFamilyIndexCount)
	if len(v.PQueueFamilyIndices) != 0 {
		enc.EncodeArraySize(uint64(len(v.PQueueFamilyIndices)))
		enc.EncodeUint32Array(v.PQueueFamilyIndices)
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeInt32(v.InitialLayout) // enum VkImageLayout
}

// EncodeVkMemoryAllocateInfo encodes a VkMemoryAllocateInfo onto enc, following Mesa
// vn_encode_VkMemoryAllocateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkMemoryAllocateInfo(enc *vncs.Encoder, v *VkMemoryAllocateInfo) {
	enc.EncodeInt32(5)             // sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeDeviceSize(v.AllocationSize)
	enc.EncodeUint32(v.MemoryTypeIndex)
}

// EncodeVkCommandPoolCreateInfo encodes a VkCommandPoolCreateInfo onto enc, following Mesa
// vn_encode_VkCommandPoolCreateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandPoolCreateInfo(enc *vncs.Encoder, v *VkCommandPoolCreateInfo) {
	enc.EncodeInt32(39)            // sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.Flags)
	enc.EncodeUint32(v.QueueFamilyIndex)
}

// EncodeVkCommandBufferAllocateInfo encodes a VkCommandBufferAllocateInfo onto enc, following Mesa
// vn_encode_VkCommandBufferAllocateInfo: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkCommandBufferAllocateInfo(enc *vncs.Encoder, v *VkCommandBufferAllocateInfo) {
	enc.EncodeInt32(40)             // sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO
	enc.EncodeSimplePointer(false)  // pNext = NULL
	enc.EncodeHandle(v.CommandPool) // handle VkCommandPool
	enc.EncodeInt32(v.Level)        // enum VkCommandBufferLevel
	enc.EncodeUint32(v.CommandBufferCount)
}

// EncodeVkImageSubresourceRange encodes a VkImageSubresourceRange onto enc, following Mesa
// vn_encode_VkImageSubresourceRange: members in declaration order (no sType/pNext).
func EncodeVkImageSubresourceRange(enc *vncs.Encoder, v *VkImageSubresourceRange) {
	enc.EncodeFlags(v.AspectMask)
	enc.EncodeUint32(v.BaseMipLevel)
	enc.EncodeUint32(v.LevelCount)
	enc.EncodeUint32(v.BaseArrayLayer)
	enc.EncodeUint32(v.LayerCount)
}

// EncodeVkClearColorValue encodes the VkClearColorValue union onto enc, following Mesa
// vn_encode_VkClearColorValue_tag: uint32 tag + array_size(4) + the 4-element arm.
func EncodeVkClearColorValue(enc *vncs.Encoder, v *VkClearColorValue) {
	enc.EncodeUint32(v.Tag)
	enc.EncodeArraySize(4)
	switch v.Tag {
	case 0:
		enc.EncodeFloat32Array(v.Float32[:])
	case 1:
		enc.EncodeInt32Array(v.Int32[:])
	case 2:
		enc.EncodeUint32Array(v.Uint32[:])
	}
}

// EncodeVkSubmitInfo encodes a VkSubmitInfo onto enc, following Mesa
// vn_encode_VkSubmitInfo: sType (int32) + the pNext chain (vn_encode_VkSubmitInfo_pnext)
// + self members in declaration order.
func EncodeVkSubmitInfo(enc *vncs.Encoder, v *VkSubmitInfo) {
	enc.EncodeInt32(4)            // sType = VK_STRUCTURE_TYPE_SUBMIT_INFO
	enc.EncodePNextChain(v.PNext) // pNext extension chain
	enc.EncodeUint32(v.WaitSemaphoreCount)
	if len(v.PWaitSemaphores) != 0 {
		enc.EncodeArraySize(uint64(len(v.PWaitSemaphores)))
		for i := range v.PWaitSemaphores {
			enc.EncodeHandle(v.PWaitSemaphores[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	if len(v.PWaitDstStageMask) != 0 {
		enc.EncodeArraySize(uint64(len(v.PWaitDstStageMask)))
		for i := range v.PWaitDstStageMask {
			enc.EncodeFlags(v.PWaitDstStageMask[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.CommandBufferCount)
	if len(v.PCommandBuffers) != 0 {
		enc.EncodeArraySize(uint64(len(v.PCommandBuffers)))
		for i := range v.PCommandBuffers {
			enc.EncodeHandle(v.PCommandBuffers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(v.SignalSemaphoreCount)
	if len(v.PSignalSemaphores) != 0 {
		enc.EncodeArraySize(uint64(len(v.PSignalSemaphores)))
		for i := range v.PSignalSemaphores {
			enc.EncodeHandle(v.PSignalSemaphores[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// EncodeVkImageMemoryBarrier encodes a VkImageMemoryBarrier onto enc, following Mesa
// vn_encode_VkImageMemoryBarrier: sType (int32) + the pNext chain (vn_encode_VkImageMemoryBarrier_pnext)
// + self members in declaration order.
func EncodeVkImageMemoryBarrier(enc *vncs.Encoder, v *VkImageMemoryBarrier) {
	enc.EncodeInt32(45)           // sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
	enc.EncodePNextChain(v.PNext) // pNext extension chain
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
	enc.EncodeInt32(v.OldLayout) // enum VkImageLayout
	enc.EncodeInt32(v.NewLayout) // enum VkImageLayout
	enc.EncodeUint32(v.SrcQueueFamilyIndex)
	enc.EncodeUint32(v.DstQueueFamilyIndex)
	enc.EncodeHandle(v.Image) // handle VkImage
	EncodeVkImageSubresourceRange(enc, &v.SubresourceRange)
}

// EncodeVkMemoryBarrier encodes a VkMemoryBarrier onto enc, following Mesa
// vn_encode_VkMemoryBarrier: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkMemoryBarrier(enc *vncs.Encoder, v *VkMemoryBarrier) {
	enc.EncodeInt32(46)            // sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
}

// EncodeVkBufferMemoryBarrier encodes a VkBufferMemoryBarrier onto enc, following Mesa
// vn_encode_VkBufferMemoryBarrier: sType (int32) + pNext (simple_pointer NULL)
// + self members in declaration order.
func EncodeVkBufferMemoryBarrier(enc *vncs.Encoder, v *VkBufferMemoryBarrier) {
	enc.EncodeInt32(44)            // sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
	enc.EncodeSimplePointer(false) // pNext = NULL
	enc.EncodeFlags(v.SrcAccessMask)
	enc.EncodeFlags(v.DstAccessMask)
	enc.EncodeUint32(v.SrcQueueFamilyIndex)
	enc.EncodeUint32(v.DstQueueFamilyIndex)
	enc.EncodeHandle(v.Buffer) // handle VkBuffer
	enc.EncodeDeviceSize(v.Offset)
	enc.EncodeDeviceSize(v.Size)
}

// Encode_vkCreateInstance frames the vkCreateInstance command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateInstance_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateInstance.
func Encode_vkCreateInstance(enc *vncs.Encoder, cmdFlags uint32, pCreateInfo *VkInstanceCreateInfo, pInstance uint64) {
	enc.EncodeInt32(0) // cmd_type = VK_COMMAND_TYPE_vkCreateInstance_EXT
	enc.EncodeFlags(cmdFlags)
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkInstanceCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pInstance != 0) {
		enc.EncodeHandle(pInstance)
	}
}

// Encode_vkEnumeratePhysicalDevices frames the vkEnumeratePhysicalDevices command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkEnumeratePhysicalDevices.
func Encode_vkEnumeratePhysicalDevices(enc *vncs.Encoder, cmdFlags uint32, instance uint64, pPhysicalDeviceCount uint32, pPhysicalDevices []uint64) {
	enc.EncodeInt32(2) // cmd_type = VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(instance) // handle VkInstance
	if enc.EncodeSimplePointer(true) {
		enc.EncodeUint32(pPhysicalDeviceCount)
	}
	if len(pPhysicalDevices) != 0 {
		enc.EncodeArraySize(uint64(len(pPhysicalDevices)))
		for i := range pPhysicalDevices {
			enc.EncodeHandle(pPhysicalDevices[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkCreateDevice frames the vkCreateDevice command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateDevice_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateDevice.
func Encode_vkCreateDevice(enc *vncs.Encoder, cmdFlags uint32, physicalDevice uint64, pCreateInfo *VkDeviceCreateInfo, pDevice uint64) {
	enc.EncodeInt32(11) // cmd_type = VK_COMMAND_TYPE_vkCreateDevice_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(physicalDevice) // handle VkPhysicalDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkDeviceCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pDevice != 0) {
		enc.EncodeHandle(pDevice)
	}
}

// Encode_vkCreateImage frames the vkCreateImage command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateImage_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateImage.
func Encode_vkCreateImage(enc *vncs.Encoder, cmdFlags uint32, device uint64, pCreateInfo *VkImageCreateInfo, pImage uint64) {
	enc.EncodeInt32(54) // cmd_type = VK_COMMAND_TYPE_vkCreateImage_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkImageCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pImage != 0) {
		enc.EncodeHandle(pImage)
	}
}

// Encode_vkAllocateMemory frames the vkAllocateMemory command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkAllocateMemory_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkAllocateMemory.
func Encode_vkAllocateMemory(enc *vncs.Encoder, cmdFlags uint32, device uint64, pAllocateInfo *VkMemoryAllocateInfo, pMemory uint64) {
	enc.EncodeInt32(21) // cmd_type = VK_COMMAND_TYPE_vkAllocateMemory_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pAllocateInfo != nil) {
		EncodeVkMemoryAllocateInfo(enc, pAllocateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pMemory != 0) {
		enc.EncodeHandle(pMemory)
	}
}

// Encode_vkCreateCommandPool frames the vkCreateCommandPool command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCreateCommandPool_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCreateCommandPool.
func Encode_vkCreateCommandPool(enc *vncs.Encoder, cmdFlags uint32, device uint64, pCreateInfo *VkCommandPoolCreateInfo, pCommandPool uint64) {
	enc.EncodeInt32(85) // cmd_type = VK_COMMAND_TYPE_vkCreateCommandPool_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(device) // handle VkDevice
	if enc.EncodeSimplePointer(pCreateInfo != nil) {
		EncodeVkCommandPoolCreateInfo(enc, pCreateInfo)
	}
	enc.EncodeSimplePointer(false) // pAllocator = NULL (Venus asserts non-NULL is unreachable)
	if enc.EncodeSimplePointer(pCommandPool != 0) {
		enc.EncodeHandle(pCommandPool)
	}
}

// Encode_vkCmdClearColorImage frames the vkCmdClearColorImage command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCmdClearColorImage_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCmdClearColorImage.
func Encode_vkCmdClearColorImage(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64, image uint64, imageLayout int32, pColor *VkClearColorValue, rangeCount uint32, pRanges []VkImageSubresourceRange) {
	enc.EncodeInt32(119) // cmd_type = VK_COMMAND_TYPE_vkCmdClearColorImage_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
	enc.EncodeHandle(image)         // handle VkImage
	enc.EncodeInt32(imageLayout)    // enum VkImageLayout
	if enc.EncodeSimplePointer(pColor != nil) {
		EncodeVkClearColorValue(enc, pColor)
	}
	enc.EncodeUint32(rangeCount)
	if len(pRanges) != 0 {
		enc.EncodeArraySize(uint64(len(pRanges)))
		for i := range pRanges {
			EncodeVkImageSubresourceRange(enc, &pRanges[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// Encode_vkQueueSubmit frames the vkQueueSubmit command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkQueueSubmit_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkQueueSubmit.
func Encode_vkQueueSubmit(enc *vncs.Encoder, cmdFlags uint32, queue uint64, submitCount uint32, pSubmits []VkSubmitInfo, fence uint64) {
	enc.EncodeInt32(18) // cmd_type = VK_COMMAND_TYPE_vkQueueSubmit_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(queue) // handle VkQueue
	enc.EncodeUint32(submitCount)
	if len(pSubmits) != 0 {
		enc.EncodeArraySize(uint64(len(pSubmits)))
		for i := range pSubmits {
			EncodeVkSubmitInfo(enc, &pSubmits[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeHandle(fence) // handle VkFence
}

// Encode_vkCmdPipelineBarrier frames the vkCmdPipelineBarrier command: VkCommandTypeEXT
// (int32 = VK_COMMAND_TYPE_vkCmdPipelineBarrier_EXT) + cmdFlags (VkFlags) + the encoded params,
// per Mesa vn_encode_vkCmdPipelineBarrier.
func Encode_vkCmdPipelineBarrier(enc *vncs.Encoder, cmdFlags uint32, commandBuffer uint64, srcStageMask uint32, dstStageMask uint32, dependencyFlags uint32, memoryBarrierCount uint32, pMemoryBarriers []VkMemoryBarrier, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers []VkBufferMemoryBarrier, imageMemoryBarrierCount uint32, pImageMemoryBarriers []VkImageMemoryBarrier) {
	enc.EncodeInt32(126) // cmd_type = VK_COMMAND_TYPE_vkCmdPipelineBarrier_EXT
	enc.EncodeFlags(cmdFlags)
	enc.EncodeHandle(commandBuffer) // handle VkCommandBuffer
	enc.EncodeFlags(srcStageMask)
	enc.EncodeFlags(dstStageMask)
	enc.EncodeFlags(dependencyFlags)
	enc.EncodeUint32(memoryBarrierCount)
	if len(pMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pMemoryBarriers)))
		for i := range pMemoryBarriers {
			EncodeVkMemoryBarrier(enc, &pMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(bufferMemoryBarrierCount)
	if len(pBufferMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pBufferMemoryBarriers)))
		for i := range pBufferMemoryBarriers {
			EncodeVkBufferMemoryBarrier(enc, &pBufferMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
	enc.EncodeUint32(imageMemoryBarrierCount)
	if len(pImageMemoryBarriers) != 0 {
		enc.EncodeArraySize(uint64(len(pImageMemoryBarriers)))
		for i := range pImageMemoryBarriers {
			EncodeVkImageMemoryBarrier(enc, &pImageMemoryBarriers[i])
		}
	} else {
		enc.EncodeArraySize(0)
	}
}

// VkCreateInstanceReplyCmdType is the VkCommandTypeEXT the vkCreateInstance reply echoes
// (VK_COMMAND_TYPE_vkCreateInstance_EXT).
const VkCreateInstanceReplyCmdType int32 = 0

// Decode_vkCreateInstance_reply decodes the vkCreateInstance reply, per Mesa
// vn_decode_vkCreateInstance_reply: command-type echo + VkResult +
// simple_pointer(pInstance). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateInstanceReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateInstance_reply(dec *vncs.Decoder) (cmdType int32, result int32, pInstance uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateInstance_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pInstance = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pInstance, ok
}

// VkCreateDeviceReplyCmdType is the VkCommandTypeEXT the vkCreateDevice reply echoes
// (VK_COMMAND_TYPE_vkCreateDevice_EXT).
const VkCreateDeviceReplyCmdType int32 = 11

// Decode_vkCreateDevice_reply decodes the vkCreateDevice reply, per Mesa
// vn_decode_vkCreateDevice_reply: command-type echo + VkResult +
// simple_pointer(pDevice). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateDeviceReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateDevice_reply(dec *vncs.Decoder) (cmdType int32, result int32, pDevice uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateDevice_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pDevice = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pDevice, ok
}

// VkCreateImageReplyCmdType is the VkCommandTypeEXT the vkCreateImage reply echoes
// (VK_COMMAND_TYPE_vkCreateImage_EXT).
const VkCreateImageReplyCmdType int32 = 54

// Decode_vkCreateImage_reply decodes the vkCreateImage reply, per Mesa
// vn_decode_vkCreateImage_reply: command-type echo + VkResult +
// simple_pointer(pImage). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateImageReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateImage_reply(dec *vncs.Decoder) (cmdType int32, result int32, pImage uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateImage_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pImage = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pImage, ok
}

// VkAllocateMemoryReplyCmdType is the VkCommandTypeEXT the vkAllocateMemory reply echoes
// (VK_COMMAND_TYPE_vkAllocateMemory_EXT).
const VkAllocateMemoryReplyCmdType int32 = 21

// Decode_vkAllocateMemory_reply decodes the vkAllocateMemory reply, per Mesa
// vn_decode_vkAllocateMemory_reply: command-type echo + VkResult +
// simple_pointer(pMemory). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkAllocateMemoryReplyCmdType (Mesa asserts the same equality).
func Decode_vkAllocateMemory_reply(dec *vncs.Decoder) (cmdType int32, result int32, pMemory uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkAllocateMemory_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pMemory = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pMemory, ok
}

// VkCreateCommandPoolReplyCmdType is the VkCommandTypeEXT the vkCreateCommandPool reply echoes
// (VK_COMMAND_TYPE_vkCreateCommandPool_EXT).
const VkCreateCommandPoolReplyCmdType int32 = 85

// Decode_vkCreateCommandPool_reply decodes the vkCreateCommandPool reply, per Mesa
// vn_decode_vkCreateCommandPool_reply: command-type echo + VkResult +
// simple_pointer(pCommandPool). ok is the simple_pointer presence flag;
// cmdType is the echoed command type the caller verifies against
// VkCreateCommandPoolReplyCmdType (Mesa asserts the same equality).
func Decode_vkCreateCommandPool_reply(dec *vncs.Decoder) (cmdType int32, result int32, pCommandPool uint64, ok bool) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkCreateCommandPool_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pCommandPool = dec.DecodeHandle()
		ok = true
	}
	return cmdType, result, pCommandPool, ok
}

// VkEnumeratePhysicalDevicesReplyCmdType is the VkCommandTypeEXT the vkEnumeratePhysicalDevices reply echoes
// (VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT).
const VkEnumeratePhysicalDevicesReplyCmdType int32 = 2

// Decode_vkEnumeratePhysicalDevices_reply decodes the vkEnumeratePhysicalDevices reply, per Mesa
// vn_decode_vkEnumeratePhysicalDevices_reply: command-type echo + VkResult +
// simple_pointer(pPhysicalDeviceCount)+uint32 + peeked counted pPhysicalDevices handle array.
// countOK is the count's simple_pointer flag; pPhysicalDevices is nil when the
// peeked array_size is 0 (the array_size(0) is still consumed, matching
// vn_decode_array_size_unchecked).
func Decode_vkEnumeratePhysicalDevices_reply(dec *vncs.Decoder) (cmdType int32, result int32, pPhysicalDeviceCount uint32, countOK bool, pPhysicalDevices []uint64) {
	cmdType = dec.DecodeInt32() // echoed VK_COMMAND_TYPE_vkEnumeratePhysicalDevices_EXT
	result = dec.DecodeResult()
	if dec.DecodeSimplePointer() {
		pPhysicalDeviceCount = dec.DecodeUint32()
		countOK = true
	}
	if dec.PeekArraySize() != 0 {
		n := dec.DecodeArraySize(uint64(pPhysicalDeviceCount))
		pPhysicalDevices = make([]uint64, n)
		for i := range pPhysicalDevices {
			pPhysicalDevices[i] = dec.DecodeHandle()
		}
	} else {
		dec.DecodeArraySizeUnchecked() // consume the array_size(0)
	}
	return cmdType, result, pPhysicalDeviceCount, countOK, pPhysicalDevices
}

// DecodeVkMemoryRequirements decodes a VkMemoryRequirements from dec, following Mesa
// vn_decode_VkMemoryRequirements: members in declaration order.
func DecodeVkMemoryRequirements(dec *vncs.Decoder, v *VkMemoryRequirements) {
	v.Size = dec.DecodeDeviceSize()
	v.Alignment = dec.DecodeDeviceSize()
	v.MemoryTypeBits = dec.DecodeUint32()
}

// DecodeVkPhysicalDeviceLimits decodes a VkPhysicalDeviceLimits from dec, following Mesa
// vn_decode_VkPhysicalDeviceLimits: members in declaration order.
func DecodeVkPhysicalDeviceLimits(dec *vncs.Decoder, v *VkPhysicalDeviceLimits) {
	v.MaxImageDimension1D = dec.DecodeUint32()
	v.MaxImageDimension2D = dec.DecodeUint32()
	v.MaxImageDimension3D = dec.DecodeUint32()
	v.MaxImageDimensionCube = dec.DecodeUint32()
	v.MaxImageArrayLayers = dec.DecodeUint32()
	v.MaxTexelBufferElements = dec.DecodeUint32()
	v.BufferImageGranularity = dec.DecodeDeviceSize()
	{
		n := dec.DecodeArraySize(3)
		copy(v.MaxComputeWorkGroupCount[:], dec.DecodeUint32Array(int(n)))
	}
	v.MaxSamplerLodBias = dec.DecodeFloat32()
	v.MinMemoryMapAlignment = dec.DecodeSizeT()
	v.MinTexelOffset = dec.DecodeInt32()
	v.FramebufferColorSampleCounts = dec.DecodeFlags()
	v.TimestampComputeAndGraphics = dec.DecodeBool32()
	{
		n := dec.DecodeArraySize(2)
		copy(v.PointSizeRange[:], dec.DecodeFloat32Array(int(n)))
	}
	v.NonCoherentAtomSize = dec.DecodeDeviceSize()
}

// DecodeVkPhysicalDeviceSparseProperties decodes a VkPhysicalDeviceSparseProperties from dec, following Mesa
// vn_decode_VkPhysicalDeviceSparseProperties: members in declaration order.
func DecodeVkPhysicalDeviceSparseProperties(dec *vncs.Decoder, v *VkPhysicalDeviceSparseProperties) {
	v.ResidencyStandard2DBlockShape = dec.DecodeBool32()
	v.ResidencyStandard2DMultisampleBlockShape = dec.DecodeBool32()
	v.ResidencyStandard3DBlockShape = dec.DecodeBool32()
	v.ResidencyAlignedMipSize = dec.DecodeBool32()
	v.ResidencyNonResidentStrict = dec.DecodeBool32()
}

// DecodeVkPhysicalDeviceProperties decodes a VkPhysicalDeviceProperties from dec, following Mesa
// vn_decode_VkPhysicalDeviceProperties: members in declaration order.
func DecodeVkPhysicalDeviceProperties(dec *vncs.Decoder, v *VkPhysicalDeviceProperties) {
	v.ApiVersion = dec.DecodeUint32()
	v.DriverVersion = dec.DecodeUint32()
	v.VendorID = dec.DecodeUint32()
	v.DeviceID = dec.DecodeUint32()
	v.DeviceType = dec.DecodeInt32() // enum VkPhysicalDeviceType
	{
		n := dec.DecodeArraySize(256)
		v.DeviceName = string(dec.DecodeCharArray(int(n)))
	}
	{
		n := dec.DecodeArraySize(16)
		v.PipelineCacheUUID = dec.DecodeUint8Array(int(n))
	}
	DecodeVkPhysicalDeviceLimits(dec, &v.Limits)
	DecodeVkPhysicalDeviceSparseProperties(dec, &v.SparseProperties)
}

// EncodeVkProtectedSubmitInfoSelf encodes just the self members of a VkProtectedSubmitInfo
// (no sType/pNext), per Mesa vn_encode_VkProtectedSubmitInfo_self — used as a pNext node.
func EncodeVkProtectedSubmitInfoSelf(enc *vncs.Encoder, v *VkProtectedSubmitInfo) {
	enc.EncodeBool32(v.ProtectedSubmit)
}

// VkProtectedSubmitInfoNode wraps v as a pNext chain node (sType VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO = 1000145000).
func VkProtectedSubmitInfoNode(v *VkProtectedSubmitInfo) vncs.PNextNode {
	return vncs.PNextNode{SType: 1000145000, EncodeSelf: func(enc *vncs.Encoder) { EncodeVkProtectedSubmitInfoSelf(enc, v) }}
}
